name: SearchX
title: SearchX Collaborative Search System
description: SearchX is a scalable collaborative search system being developed by Lambda Lab of TU Delft.
tags:
  - search system
  - collaborative search
  - information retrieval
  - tu delft
  - collaborative search engine
email: f.moraes@tudelft.nl
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
